# Site settings
title: Mapping Documentation
description: Documentation for mapping
baseurl: "/mapping-documentation"

# Theme settings
theme: jekyll-theme-hacker #jekyll-theme-tactile #jekyll-theme-slate # jekyll-theme-minimal
show_downloads: false

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
