# Site settings
title: Mapping Documentation
description: Documentation for mapping
theme: jekyll-theme-minimal
baseurl: "/mapping-documentation"

# Theme settings
theme: jekyll-theme-cayman
show_downloads: false

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

menu:
  - name: "Home"
    url: "/"
  - name: "Route map"
    url: "/route/"
  - name: "Route landing page maps"
    url: "/route-landing-page/"
  - name: "Paragraphs"
    url: "/paragraph-embeds/"
  - name: "Modules"
    url: "/modules/"
  - name: "Listings"
    url: "/listings-pages/"
  - name: "Journey planner"
    url: "/journey-planner/"
